# Generated by Django 5.1.1 on 2024-10-24 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gendertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='groupmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hr.groupmodel')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='emp')),
                ('employee_code', models.CharField(max_length=225)),
                ('employee_eng_name', models.CharField(max_length=225)),
                ('employee_mm_name', models.CharField(max_length=225)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('point', models.CharField(blank=True, max_length=255, null=True)),
                ('nrc_no', models.CharField(max_length=225)),
                ('ssb_no', models.CharField(blank=True, max_length=225, null=True)),
                ('mobile', models.CharField(blank=True, max_length=225, null=True)),
                ('gender', models.CharField(max_length=225)),
                ('address', models.TextField()),
                ('resign', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hr.department')),
                ('group_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hr.groupmodel')),
                ('region', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hr.region')),
            ],
        ),
    ]
